name: Store and Retrieve Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-artifact:
    name: Generate and Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Output File
        run: echo "This is the output from Job 1" > output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: job-output
          path: output.txt
          retention-days: 5  # Automatically deletes after 5 days

