name: Store and Retrieve Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-artifact:
    name: Generate and Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Output File
        run: echo "This is the output from Job 1" > output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: job-output
          path: output.txt
          retention-days: 5  # Automatically deletes after 5 days
  use-artifact:
   name: Download and Use Artifact
   runs-on: ubuntu-latest
   needs: generate-artifact  # Ensures Job 1 runs first
   steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: job-output
          path: .

      - name: Display Artifact Content
        run: cat output.txt


